# Generated by Django 4.1.4 on 2023-01-13 01:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_note', models.CharField(max_length=100)),
                ('body', models.TextField(max_length=2000)),
                ('name_customer', models.CharField(max_length=250)),
                ('name_recibe', models.CharField(default='', max_length=250)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('anotations', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(default='NA', max_length=250)),
                ('product', models.CharField(default=None, max_length=250, null=True)),
                ('customer', models.CharField(default='dona nona', max_length=250)),
                ('unit_price', models.FloatField(default=0.0)),
                ('qty', models.IntegerField(default=0)),
                ('subtotal', models.FloatField(default=0.0)),
                ('total', models.FloatField(default=0.0)),
                ('date', models.CharField(default='NA', max_length=250)),
                ('status', models.IntegerField(choices=[(1, 'procesando'), (2, 'entregado'), (3, 'cancelado')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Tokens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=250)),
                ('refresh_token', models.CharField(max_length=250)),
                ('is_update', models.BooleanField(default=False)),
                ('last_update', models.DateTimeField(default=datetime.datetime(2023, 1, 13, 1, 5, 18, 958093, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250)),
                ('descripcion', models.CharField(max_length=250)),
                ('sku', models.CharField(default='0', max_length=250)),
                ('costo', models.FloatField()),
                ('precio', models.FloatField()),
                ('margen', models.FloatField(default='0')),
                ('existencia', models.IntegerField(default='0')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='productos_cat', to='inventario.categoria')),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Linea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('nota_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas_nota', to='inventario.nota')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
            ],
        ),
    ]
