# Generated by Django 4.1.4 on 2023-01-13 01:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_tokens_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokens',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 13, 1, 33, 46, 577523, tzinfo=datetime.timezone.utc)),
        ),
    ]
