# Generated by Django 4.1.5 on 2023-01-21 03:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_order_notas_alter_tokens_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokens',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 21, 3, 55, 51, 685838, tzinfo=datetime.timezone.utc)),
        ),
    ]
