# Generated by Django 5.0 on 2023-12-25 05:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_alter_order_status_alter_tokens_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokens',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 25, 5, 58, 1, 636227, tzinfo=datetime.timezone.utc)),
        ),
    ]
