# Generated by Django 5.0 on 2024-07-03 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_alter_tokens_last_update'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(name='Order'),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name='Order',
                    table='ordenes_order'
                )
            ]
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(name='Tokens'),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name='Tokens',
                    table='ordenes_tokens'
                )
            ]
        ),
    ]

    # migrations.DeleteModel(
    #    name='Order',
    # ),
    # migrations.DeleteModel(
    #    name='Tokens',
    # ),
    # ,
