# Generated by Django 5.0 on 2024-07-02 20:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ordenes', '0001_inicial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Order',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('order_id', models.CharField(default='NA', max_length=250)),
                        ('product', models.CharField(default=None, max_length=250, null=True)),
                        ('customer', models.CharField(default='NA', max_length=250)),
                        ('unit_price', models.FloatField(default=0.0)),
                        ('qty', models.IntegerField(default=0)),
                        ('subtotal', models.FloatField(default=0.0)),
                        ('total', models.FloatField(default=0.0)),
                        ('date', models.CharField(default='NA', max_length=250)),
                        ('status', models.CharField(default='NA', max_length=250)),
                        ('notas', models.CharField(db_index=True, default='NA', max_length=250)),
                    ],
                ),
            ],
            database_operations=[]
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Tokens',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('token', models.CharField(max_length=250)),
                        ('refresh_token', models.CharField(max_length=250)),
                        ('is_update', models.BooleanField(default=False)),
                        ('last_update', models.DateTimeField(default=datetime.datetime(2024, 7, 2, 20, 29, 0, 145528, tzinfo=datetime.timezone.utc))),
                    ],
                ),
            ],
            database_operations=[]
        )
    ]


    '''
     migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(default='NA', max_length=250)),
                ('product', models.CharField(default=None, max_length=250, null=True)),
                ('customer', models.CharField(default='NA', max_length=250)),
                ('unit_price', models.FloatField(default=0.0)),
                ('qty', models.IntegerField(default=0)),
                ('subtotal', models.FloatField(default=0.0)),
                ('total', models.FloatField(default=0.0)),
                ('date', models.CharField(default='NA', max_length=250)),
                ('status', models.CharField(default='NA', max_length=250)),
                ('notas', models.CharField(db_index=True, default='NA', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Tokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=250)),
                ('refresh_token', models.CharField(max_length=250)),
                ('is_update', models.BooleanField(default=False)),
                ('last_update', models.DateTimeField(default=datetime.datetime(2024, 7, 2, 20, 29, 0, 145528, tzinfo=datetime.timezone.utc))),
            ],
        ),
    '''
