# Generated by Django 5.0 on 2024-07-16 01:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokens',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 16, 1, 22, 17, 475387, tzinfo=datetime.timezone.utc)),
        ),
    ]
