# Generated by Django 5.0 on 2024-07-17 02:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0003_alter_tokens_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokens',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 17, 2, 22, 47, 624584, tzinfo=datetime.timezone.utc)),
        ),
    ]
