# Generated by Django 5.0 on 2024-07-30 16:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0004_alter_tokens_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokens',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 30, 16, 56, 51, 410206, tzinfo=datetime.timezone.utc)),
        ),
    ]
