# Generated by Django 5.0 on 2024-08-02 03:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0006_alter_tokens_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokens',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 2, 3, 16, 39, 93879, tzinfo=datetime.timezone.utc)),
        ),
    ]
