# Generated by Django 5.0 on 2024-08-10 00:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0007_alter_tokens_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokens',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 10, 0, 14, 35, 611264, tzinfo=datetime.timezone.utc)),
        ),
    ]
