# Generated by Django 5.0 on 2024-09-18 22:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0008_alter_tokens_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokens',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 18, 22, 31, 2, 245234, tzinfo=datetime.timezone.utc)),
        ),
    ]
