# Generated by Django 5.0 on 2024-07-30 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('porcentaje_anual', models.FloatField()),
                ('congelamiento_dias', models.FloatField()),
                ('monto', models.FloatField()),
                ('gains_mes', models.FloatField()),
                ('gains_anual', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Metricas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_inversion', models.FloatField()),
                ('prom_porcentaje_anual', models.FloatField()),
                ('gains_mes', models.FloatField()),
                ('gains_anual', models.FloatField()),
                ('instrumentos', models.ManyToManyField(to='board.instrumento')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metricas_profile', to='board.profile')),
            ],
        ),
    ]
