# Generated by Django 5.0 on 2024-07-30 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_instrumento_metricas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrumento',
            name='gains_anual',
        ),
        migrations.RemoveField(
            model_name='instrumento',
            name='gains_mes',
        ),
    ]
