# Generated by Django 5.0 on 2024-08-02 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_remove_instrumento_gains_anual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metricas',
            name='gains_anual',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='metricas',
            name='gains_mes',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='metricas',
            name='prom_porcentaje_anual',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='metricas',
            name='total_inversion',
            field=models.FloatField(default=0),
        ),
    ]
