# Generated by Django 5.0 on 2024-08-10 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_alter_metricas_gains_anual_alter_metricas_gains_mes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GainDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=250)),
                ('mount', models.FloatField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='instrumento',
            name='congelamiento_dias',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='instrumento',
            name='monto',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='instrumento',
            name='porcentaje_anual',
            field=models.FloatField(default=0),
        ),
    ]
