# Generated by Django 5.0 on 2024-09-18 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_gainday_alter_instrumento_congelamiento_dias_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metricas',
            name='gains_anual',
        ),
        migrations.RemoveField(
            model_name='metricas',
            name='gains_mes',
        ),
        migrations.RemoveField(
            model_name='metricas',
            name='prom_porcentaje_anual',
        ),
        migrations.RemoveField(
            model_name='metricas',
            name='total_inversion',
        ),
    ]
